project_id = "fsoqhhqbtmessubsxhsp"

[functions.scrape-product]
verify_jwt = true

[functions.send-price-alert]
verify_jwt = true

[functions.price-monitor]
verify_jwt = true

[functions.refresh-product-images]
verify_jwt = false
