// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fsoqhhqbtmessubsxhsp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZzb3FoaHFidG1lc3N1YnN4aHNwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAzNzExOTcsImV4cCI6MjA2NTk0NzE5N30.swJkiES5X1jdaAnfBuUnCMHZSXRaTq6yud79S_deNLk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);